package Layer;

import java.util.HashMap;

public class Constant {
	 public static final HashMap<Integer,String> HTYPE = new HashMap<Integer,String>() 
	 {{  
		 put(1,"Ethernet");
		 put(6,"IEEE 802 Networks");
		 put(7,"ARCNET");
		 put(11,"LocalTalk");
		 put(12,"LocalNet");
		 put(14,"SMDS");
		 put(15,"Frame Delay");
		 put(16,"Asynchronous Transger Mode(ATM)");
		 put(17,"HDLC");
		 put(18,"Fibre Channel");
		 put(19,"Asynchronous Transger Mode(ATM");
		 put(20,"Serail line");
		 }};
	public static final HashMap <Integer, String> DHCPOPTION =  new HashMap<Integer,String>()
	{{
		put(0,"Pad");
		put(1,"Subnet Mask");
		put(2,"Time Offset");
		put(3,"Router");
		put(4,"Time Server");
		put(5,"Name Server");
		put(6,"Domain Server");
		put(7,"Log Server");
		put(8,"Quotes Server");
		put(9,"LPR Server");
		put(10,"Impress Server");
		put(11,"RLP Server");
		put(12,"Hostname");
		put(13,"Boot File Size");
		put(14,"Merit Dump File");
		put(15,"Domain Name");
		put(16,"Swap Server");
		put(17,"Root Path");
		put(18,"Extension File");
		put(19,"Forward On/Off");
		put(20,"SrcRte On/Off");
		put(21,"Policy Filter");
		put(22,"Max DG Assembly");
		put(23,"Default IP TTL");
		put(24,"MTU Timeout");
		put(25,"MTU Plateau	");
		put(26,"MTU Interface");
		put(27,"MTU Subnet");
		put(28,"Broadcast Address");
		put(29,"Mask Discovery");
		put(30,"Mask Supplier");
		put(31,"Router Discovery");
		put(32,"Router Request");
		put(33,"Static Route");
		put(34,"Trailers");
		put(35,"ARP Timeout");
		put(36,"Ethernet");
		put(37,"Default TCP TTL");
		put(38,"Keepalive Time");
		put(39,"Keepalive Data");
		put(40,"NIS Domain");
		put(41,"NIS Servers");
		put(42,"NTP Servers");
		put(43,"Vendor Specific");
		put(44,"NETBIOS Name Srv");
		put(45,"NETBIOS Dist Srv");
		put(46,"NETBIOS Node Type");
		put(47,"NETBIOS Scope");
		put(48,"X Window Font");
		put(49,"X Window Manager");
		put(50,"Address Request");
		put(51,"Address Time");
		put(52,"Overload");
		put(53,"DHCP Msg Type");
		put(54,"DHCP Server Id");
		put(55,"Parameter List");
		put(56,"DHCP Message");
		put(57,"DHCP Max Msg Size");
		put(58,"Renewal Time");
		put(59,"Rebinding Time");
		put(60,"Class Id");
		put(61,"Client Id");
		put(62,"NetWare/IP Domain");
		put(63,"NetWare/IP Option");
		put(64,"NIS-Domain-Name");
		put(65,"NIS-Server-Addr");
		put(66,"Server-Name");
		put(67,"Bootfile-Name");
		put(68,"Home-Agent-Addrs");
		put(69,"SMTP-Server");
		put(70,"POP3-Server");
		put(71,"NNTP-Server");
		put(72,"WWW-Server");
		put(73,"Finger-Server");
		put(74,"Finger-IRC-Server");
		put(75,"StreetTalk-Server");
		put(76,"STDA-Server");
		put(77,"User-Class");
		put(78,"Directory Agent");
		put(79,"Service Scope");
		put(80,"Rapid Commit");
		put(81,"Client FQDN");
		put(82,"Relay Agent Information");
		put(83,"iSNS");
		put(84,"REMOVED/Unassigned");
		put(85,"NDS Servers");
		put(86,"NDS Tree Name");
		put(87,"NDS Context");
		put(88,"BCMCS Controller Domain Name list");
		put(89,"BCMCS Controller IPv4 address option");
		put(90,"Authentication");
		put(91,"client-last-transaction-time option");
		put(92,"associated-ip option");
		put(93,"Client System");
		put(94,"Client NDI");
		put(95,"LDAP");
		put(96,"REMOVED/Unassigned");
		put(97,"UUID/GUID");
		put(98,"User-Auth");
		put(99,"GEOCONF_CIVIC");
		put(100,"PCode");
		put(101,"TCode");
		put(108,"IPv6-Only Preferred");
		put(109,"OPTION_DHCP4O6_S46_SADDR");
		put(112,"Netinfo Address");
		put(113,"Netinfo Tag");
		put(114,"DHCP Captive-Portal");
		put(115,"REMOVED/Unassigned");
		put(116,"Auto-Config");
		put(117,"Name Service Search");
		put(118,"Subnet Selection Option");
		put(119,"Domain Search");
		put(120,"SIP Servers DHCP Option");
		put(121,"Classless Static Route Option");
		put(122,"CCC");
		put(123,"GeoConf Option");
		put(124,"V-I Vendor Class");
		put(125,"V-I Vendor-Specific Information");
		put(126,"Removed/Unassigned");
		put(127,"Removed/Unassigned");
		put(128,"PXE - undefined (vendor specific)");
		put(129,"Call Server IP Address");
		put(130,"Discrimination String");
		put(131,"Remote Statistics Server IP Address");
		put(132,"802.1Q VLAN ID");
		put(133,"802.1Q L2 Priority");
		put(134,"Diffserv Code Poin");
		put(135,"HTTP Proxy For Phone Applications");
		put(150,"TFTP Server Address, Etherboot, GRUB Config");
		put(177,"Ether Boot PacketCable and CableHome");
		put(208,"PXELINUX Magic");
		put(209,"Configuration File");
		put(210,"Path Prefix");
		put(211,"Reboot Time");
		put(220,"Subnet Allocation");
		put(221,"Virtual Subnet Allocation");
		put(255,"END");
		put(256,"Unknow Option");
		}};
		public static final HashMap<Integer,String> DHCP_MESSAGE_TYPE = new HashMap<Integer,String>()
		{{
			put(1,"Discover");
			put(2,"Offer");
			put(3,"Request");
			put(4,"Decline");
			put(5,"ACK");
			put(6,"NAK");
			put(7,"Release");
			put(8,"Informational");
		}};
				
}
